### PR TITLE
spacing polish

### PR DESCRIPTION
**Pull request by kimby77**
Polished css spacing.

@hdahme

### CODE REVIEW

**Comment by hdahme** [comment]
Okie =)

Screenshot please!

**Comment by kimby77** [comment]
The html wasn't opening right for me in my browser so there wasn't really a screenshot to take :/

**Comment by kimby77** [comment]
OH. The style sheet wasn't linked into the html.  That's why it wasn't showing up.

Screenshot:
image

**Comment by hdahme** [comment]
Nice. Push it.

Yeah, I took the linking out in the HTML since NR would have serious issues if it was linked

**Pull request merged**
